---

- name: PROXYSQL | Dependencies
  include_tasks: dependencies.yml
  tags:
    - proxysql_dependencies

- name: PROXYSQL | Install
  include_tasks: "{{ proxysql_from }}_install.yml"
  tags:
    - proxysql_install

- name: PROXYSQL | SSL Configure
  include_tasks: ssl_config.yml
  when: proxysql_ssl_config
  tags:
    - proxysql_ssl_configure

- name: PROXYSQL | Configure
  include_tasks: config.yml
  tags:
    - proxysql_configure
