---

- name: PROXYSQL | Dependencies
  include: dependencies.yml
  tags:
    - proxysql_dependencies

- name: PROXYSQL | Install
  include: "{{ proxysql_from }}_install.yml"
  tags:
    - proxysql_install

- name: PROXYSQL | SSL Configure
  include: ssl_config.yml
  when: proxysql_ssl_config
  tags:
    - proxysql_ssl_configure

- name: PROXYSQL | Configure
  include: config.yml
  tags:
    - proxysql_configure
