---

- name: PROXYSQL OFFICIAL | Gather OS specific variables
  include_vars: "{{ proxysql_from }}.yml"
  tags:
    - proxysql_install

- name: PROXYSQL OFFICIAL | Check proxysql version
  command: "{{ proxysql_exec_name }} --version"
  register: proxysql_check
  changed_when: false
  ignore_errors: true
  check_mode: no
  tags:
    - proxysql_install

- block:
    - name: PROXYSQL OFFICIAL | Add Repo Key
      apt_key:
        url: "{{ proxysql_key_url }}"
        state: present

    - name: PROXYSQL OFFICIAL | Add specified repository into sources list
      apt_repository:
        repo: "deb {{ proxysql_deb_repo }} ./"
        state: present
        filename: proxysql

    - name: PROXYSQL OFFICIAL | Update cache
      apt:
        update_cache: true
        allow_unauthenticated: true
      changed_when: false

    - name: PROXYSQL OFFICIAL | Installing packages
      apt:
        pkg: "{{ proxysql_packages }}"
        state: present
  when: proxysql_force_reinstall or proxysql_check is failed or proxysql_version not in proxysql_check.stdout
  tags:
    - proxysql_install
