---

proxysql_backend_servers:
  - hostgroup_id: 0
    hostname: backend1
    port: 3306
  - hostgroup_id: 0
    hostname: backend2
    port: 3306
  - hostgroup_id: 0
    hostname: backend3
    port: 3306

proxysql_global_variables:
  - key: mysql-monitor_username
    value: monitor
  - key: mysql-monitor_password
    value: monitor
  - key: mysql-monitor_connect_interval
    value: 2000
  - key: mysql-monitor_ping_interval
    value: 2000
  - key: mysql-monitor_read_only_interval
    value: 2000
  - key: mysql-max_connections
    value: 5000
  - key: mysql-server_version
    value: 8.0

proxysql_replication_hostgroups:
  - writer_hostgroup: 1
    reader_hostgroup: 2

proxysql_mysql_users:
  - username: proxysql_test
    password: proxysql_test
    default_hostgroup: 1

proxysql_query_rules:
  - rule_id: 1
    active: true
    username: test
    match_digest: "^SELECT c FROM sbtest1 WHERE id=\\?$"
    destination_hostgroup: 1
    apply: true
